`ifndef AXI4_MASTER_SAME_ID_NONADJACENT_READ_SEQ_INCLUDED_
`define AXI4_MASTER_SAME_ID_NONADJACENT_READ_SEQ_INCLUDED_

//--------------------------------------------------------------------------------------------
// Class: axi4_master_same_id_nonadjacent_read_seq
//
// Measure half of the AXI_ooo.md Finding F2 (P0.2) reproduction: NON-ADJACENT
// same-ARID reads against a slave in ONLY_READ_RESP_OUT_OF_ORDER.
//
// THE BUG BEING PROVOKED (slave/axi4_slave_driver_proxy.sv:801-816)
//   When an AR is accepted, the slave decides whether it must keep this transaction
//   in strict order with an earlier one by comparing the new ARID against the TAIL of
//   the outstanding queue only:
//         oor_struct_read_packet = rd_response_id_queue[$];
//         if(struct_read_packet.arid == oor_struct_read_packet.arid) ...
//   So for the id sequence A,B,A the second A does not match tail B, and BOTH A
//   transactions end up sitting in rd_response_id_queue together. That queue is then
//   shuffled before every pop (`:1782-1783`), which can return the LATER A's response
//   first. AXI4 requires responses with the same ARID to be returned in the order the
//   addresses were issued, so this is a protocol violation generated by the VIP
//   itself, not by any DUT.
//
// WHAT MAKES IT OBSERVABLE
//   Every SLOT (issue position) reads a different 4KB page carrying a different
//   payload -- see axi4_master_same_id_nonadjacent_preload_seq for the slot maps.
//   Two occurrences of id A therefore return DIFFERENT data, so "the wrong A came
//   back first" is visible in the R data alone. With an id-keyed payload (the scheme
//   the cross-ID reorder sequences use) the two A responses would be identical and
//   the violation would be undetectable by construction.
//
// EXPECTED SYMPTOM BEFORE THE FIX (Phase 2 of AXI_ooo.md)
//   The provisional probe in axi4_same_id_nonadjacent_reorder_test reports
//   "SAME-ID ORDER VIOLATION": an R burst joined to ARADDR = page N carries the
//   payload planted at page M, M != N. That is the master monitor's per-RID
//   pop_front() (master/axi4_master_monitor_proxy.sv:363) faithfully attributing the
//   first RID=A burst to the first outstanding ARID=A read -- which is the correct
//   thing to do, and is only wrong because the slave answered out of order.
//
// EXPECTED AFTER THE FIX
//   Every R burst's data matches the page its ARADDR names; probe mismatch count 0.
//
// NOTE ON REPRODUCTION RATE
//   This is statistical: rd_response_id_queue.shuffle() may happen to produce issue
//   order. num_rounds x 3 occurrences of id A per run and several seeds are what make
//   it dependable; record the seed with any result.
//--------------------------------------------------------------------------------------------
class axi4_master_same_id_nonadjacent_read_seq extends axi4_master_nbk_base_seq;
  `uvm_object_utils(axi4_master_same_id_nonadjacent_read_seq)

  // Keep these two in step with the preload sequence.
  int unsigned num_rounds = 4;
  bit [63:0]   base_addr  = 64'h0000_0000_0000_1000;

  function new(string name = "axi4_master_same_id_nonadjacent_read_seq");
    super.new(name);
  endfunction : new

  task body();
    // super.body() intentionally not called -- N reads are outstanding at once.
    automatic int unsigned n_slots =
      axi4_master_same_id_nonadjacent_preload_seq::slots_for_rounds(num_rounds);

    for (int unsigned s = 0; s < n_slots; s++) begin
      automatic int unsigned id_val =
        axi4_master_same_id_nonadjacent_preload_seq::id_for_slot(s);
      automatic bit [63:0]   addr =
        axi4_master_same_id_nonadjacent_preload_seq::addr_for_slot(base_addr, s);
      automatic bit [31:0]   expected_data =
        axi4_master_same_id_nonadjacent_preload_seq::data_for_slot(s);
      // Explicit cast: the helper macro is a ternary chain.
      automatic arid_e       arid_v = arid_e'(`GET_ARID_ENUM(id_val));
      axi4_master_tx         tx;

      tx = axi4_master_tx::type_id::create($sformatf("same_id_rd_%0d", s));
      start_item(tx);
      if (!tx.randomize() with {
        tx.tx_type       == READ;
        tx.transfer_type == NON_BLOCKING_READ;
        tx.arid          == local::arid_v;
        tx.araddr        == local::addr;
        tx.arlen         == 0;
        tx.arsize        == READ_4_BYTES;
        tx.arburst       == READ_INCR;
        tx.arlock        == READ_NORMAL_ACCESS;
        tx.arcache       == 4'h0;
        tx.arprot        == 3'h0;
        tx.aruser        == 4'h0;
      }) begin
        `uvm_fatal(get_type_name(),
                   $sformatf("randomize() failed for same-ID read slot=%0d addr=0x%0h", s, addr))
      end

      // ISSUE-ORDER LINE. Grep "SAMEID_READ issue" and compare against the
      // "SAMEID_READ complete" lines the test's probe prints.
      `uvm_info(get_type_name(),
                $sformatf("SAMEID_READ issue slot=%0d: ARID=%s ADDR=0x%016h EXPECT_DATA=0x%08h",
                          s, arid_v.name(), addr, expected_data), UVM_LOW)

      // Returns at the AR handshake, so every AR of the pattern becomes outstanding
      // together and the slave has a backlog to shuffle.
      finish_item(tx);
    end
  endtask : body

endclass : axi4_master_same_id_nonadjacent_read_seq

`endif
