//------------------------------------------------------------------------------
// axi4_nic400_fabric_wrapper
//
// GENERATED from nic400_vip4x4q.v -- do not hand edit.
//
// Presents the flat, per-port NIC-400 fabric top (nic400_vip4x4q) as vectorised
// buses so hdl_top can connect the VIP interface arrays in a generate loop.
//
//   m_*  : fabric INGRESS  (fabric AXI4_Slave<N>)  <- VIP master agents drive
//   s_*  : fabric EGRESS   (fabric AXI4_Master<N>) -> VIP slave  agents respond
//------------------------------------------------------------------------------
`ifndef AXI4_NIC400_FABRIC_WRAPPER_INCLUDED_
`define AXI4_NIC400_FABRIC_WRAPPER_INCLUDED_

module axi4_nic400_fabric_wrapper #(
  parameter int NUM = 4
) (
  input logic clk,
  input logic resetn,

  input  logic [NUM-1:0][63:0] m_araddr,
  input  logic [NUM-1:0][1:0] m_arburst,
  input  logic [NUM-1:0][3:0] m_arcache,
  input  logic [NUM-1:0][3:0] m_arid,
  input  logic [NUM-1:0][7:0] m_arlen,
  input  logic [NUM-1:0] m_arlock,
  input  logic [NUM-1:0][2:0] m_arprot,
  input  logic [NUM-1:0][3:0] m_arqos,
  output logic [NUM-1:0] m_arready,
  input  logic [NUM-1:0][3:0] m_arregion,
  input  logic [NUM-1:0][2:0] m_arsize,
  input  logic [NUM-1:0][31:0] m_aruser,
  input  logic [NUM-1:0] m_arvalid,
  input  logic [NUM-1:0][63:0] m_awaddr,
  input  logic [NUM-1:0][1:0] m_awburst,
  input  logic [NUM-1:0][3:0] m_awcache,
  input  logic [NUM-1:0][3:0] m_awid,
  input  logic [NUM-1:0][7:0] m_awlen,
  input  logic [NUM-1:0] m_awlock,
  input  logic [NUM-1:0][2:0] m_awprot,
  input  logic [NUM-1:0][3:0] m_awqos,
  output logic [NUM-1:0] m_awready,
  input  logic [NUM-1:0][3:0] m_awregion,
  input  logic [NUM-1:0][2:0] m_awsize,
  input  logic [NUM-1:0][31:0] m_awuser,
  input  logic [NUM-1:0] m_awvalid,
  output logic [NUM-1:0][3:0] m_bid,
  input  logic [NUM-1:0] m_bready,
  output logic [NUM-1:0][1:0] m_bresp,
  output logic [NUM-1:0][15:0] m_buser,
  output logic [NUM-1:0] m_bvalid,
  output logic [NUM-1:0][255:0] m_rdata,
  output logic [NUM-1:0][3:0] m_rid,
  output logic [NUM-1:0] m_rlast,
  input  logic [NUM-1:0] m_rready,
  output logic [NUM-1:0][1:0] m_rresp,
  output logic [NUM-1:0][15:0] m_ruser,
  output logic [NUM-1:0] m_rvalid,
  input  logic [NUM-1:0][255:0] m_wdata,
  input  logic [NUM-1:0] m_wlast,
  output logic [NUM-1:0] m_wready,
  input  logic [NUM-1:0][31:0] m_wstrb,
  input  logic [NUM-1:0][31:0] m_wuser,
  input  logic [NUM-1:0] m_wvalid,
  output logic [NUM-1:0][63:0] s_araddr,
  output logic [NUM-1:0][1:0] s_arburst,
  output logic [NUM-1:0][3:0] s_arcache,
  output logic [NUM-1:0][5:0] s_arid,
  output logic [NUM-1:0][7:0] s_arlen,
  output logic [NUM-1:0] s_arlock,
  output logic [NUM-1:0][2:0] s_arprot,
  input  logic [NUM-1:0] s_arready,
  output logic [NUM-1:0][3:0] s_arregion,
  output logic [NUM-1:0][2:0] s_arsize,
  output logic [NUM-1:0][31:0] s_aruser,
  output logic [NUM-1:0] s_arvalid,
  output logic [NUM-1:0][63:0] s_awaddr,
  output logic [NUM-1:0][1:0] s_awburst,
  output logic [NUM-1:0][3:0] s_awcache,
  output logic [NUM-1:0][5:0] s_awid,
  output logic [NUM-1:0][7:0] s_awlen,
  output logic [NUM-1:0] s_awlock,
  output logic [NUM-1:0][2:0] s_awprot,
  input  logic [NUM-1:0] s_awready,
  output logic [NUM-1:0][3:0] s_awregion,
  output logic [NUM-1:0][2:0] s_awsize,
  output logic [NUM-1:0][31:0] s_awuser,
  output logic [NUM-1:0] s_awvalid,
  input  logic [NUM-1:0][5:0] s_bid,
  output logic [NUM-1:0] s_bready,
  input  logic [NUM-1:0][1:0] s_bresp,
  input  logic [NUM-1:0][15:0] s_buser,
  input  logic [NUM-1:0] s_bvalid,
  input  logic [NUM-1:0][255:0] s_rdata,
  input  logic [NUM-1:0][5:0] s_rid,
  input  logic [NUM-1:0] s_rlast,
  output logic [NUM-1:0] s_rready,
  input  logic [NUM-1:0][1:0] s_rresp,
  input  logic [NUM-1:0][15:0] s_ruser,
  input  logic [NUM-1:0] s_rvalid,
  output logic [NUM-1:0][255:0] s_wdata,
  output logic [NUM-1:0] s_wlast,
  input  logic [NUM-1:0] s_wready,
  output logic [NUM-1:0][31:0] s_wstrb,
  output logic [NUM-1:0][31:0] s_wuser,
  output logic [NUM-1:0] s_wvalid
);

  nic400_vip4x4q u_fabric (
    .clk0clk(clk),
    .clk0resetn(resetn),
    .ARADDR_AXI4_Slave0(m_araddr[0]),
    .ARADDR_AXI4_Slave1(m_araddr[1]),
    .ARADDR_AXI4_Slave2(m_araddr[2]),
    .ARADDR_AXI4_Slave3(m_araddr[3]),
    .ARBURST_AXI4_Slave0(m_arburst[0]),
    .ARBURST_AXI4_Slave1(m_arburst[1]),
    .ARBURST_AXI4_Slave2(m_arburst[2]),
    .ARBURST_AXI4_Slave3(m_arburst[3]),
    .ARCACHE_AXI4_Slave0(m_arcache[0]),
    .ARCACHE_AXI4_Slave1(m_arcache[1]),
    .ARCACHE_AXI4_Slave2(m_arcache[2]),
    .ARCACHE_AXI4_Slave3(m_arcache[3]),
    .ARID_AXI4_Slave0(m_arid[0]),
    .ARID_AXI4_Slave1(m_arid[1]),
    .ARID_AXI4_Slave2(m_arid[2]),
    .ARID_AXI4_Slave3(m_arid[3]),
    .ARLEN_AXI4_Slave0(m_arlen[0]),
    .ARLEN_AXI4_Slave1(m_arlen[1]),
    .ARLEN_AXI4_Slave2(m_arlen[2]),
    .ARLEN_AXI4_Slave3(m_arlen[3]),
    .ARLOCK_AXI4_Slave0(m_arlock[0]),
    .ARLOCK_AXI4_Slave1(m_arlock[1]),
    .ARLOCK_AXI4_Slave2(m_arlock[2]),
    .ARLOCK_AXI4_Slave3(m_arlock[3]),
    .ARPROT_AXI4_Slave0(m_arprot[0]),
    .ARPROT_AXI4_Slave1(m_arprot[1]),
    .ARPROT_AXI4_Slave2(m_arprot[2]),
    .ARPROT_AXI4_Slave3(m_arprot[3]),
    .ARQOS_AXI4_Slave0(m_arqos[0]),
    .ARQOS_AXI4_Slave1(m_arqos[1]),
    .ARQOS_AXI4_Slave2(m_arqos[2]),
    .ARQOS_AXI4_Slave3(m_arqos[3]),
    .ARREADY_AXI4_Slave0(m_arready[0]),
    .ARREADY_AXI4_Slave1(m_arready[1]),
    .ARREADY_AXI4_Slave2(m_arready[2]),
    .ARREADY_AXI4_Slave3(m_arready[3]),
    .ARREGION_AXI4_Slave0(m_arregion[0]),
    .ARREGION_AXI4_Slave1(m_arregion[1]),
    .ARREGION_AXI4_Slave2(m_arregion[2]),
    .ARREGION_AXI4_Slave3(m_arregion[3]),
    .ARSIZE_AXI4_Slave0(m_arsize[0]),
    .ARSIZE_AXI4_Slave1(m_arsize[1]),
    .ARSIZE_AXI4_Slave2(m_arsize[2]),
    .ARSIZE_AXI4_Slave3(m_arsize[3]),
    .ARUSER_AXI4_Slave0(m_aruser[0]),
    .ARUSER_AXI4_Slave1(m_aruser[1]),
    .ARUSER_AXI4_Slave2(m_aruser[2]),
    .ARUSER_AXI4_Slave3(m_aruser[3]),
    .ARVALID_AXI4_Slave0(m_arvalid[0]),
    .ARVALID_AXI4_Slave1(m_arvalid[1]),
    .ARVALID_AXI4_Slave2(m_arvalid[2]),
    .ARVALID_AXI4_Slave3(m_arvalid[3]),
    .AWADDR_AXI4_Slave0(m_awaddr[0]),
    .AWADDR_AXI4_Slave1(m_awaddr[1]),
    .AWADDR_AXI4_Slave2(m_awaddr[2]),
    .AWADDR_AXI4_Slave3(m_awaddr[3]),
    .AWBURST_AXI4_Slave0(m_awburst[0]),
    .AWBURST_AXI4_Slave1(m_awburst[1]),
    .AWBURST_AXI4_Slave2(m_awburst[2]),
    .AWBURST_AXI4_Slave3(m_awburst[3]),
    .AWCACHE_AXI4_Slave0(m_awcache[0]),
    .AWCACHE_AXI4_Slave1(m_awcache[1]),
    .AWCACHE_AXI4_Slave2(m_awcache[2]),
    .AWCACHE_AXI4_Slave3(m_awcache[3]),
    .AWID_AXI4_Slave0(m_awid[0]),
    .AWID_AXI4_Slave1(m_awid[1]),
    .AWID_AXI4_Slave2(m_awid[2]),
    .AWID_AXI4_Slave3(m_awid[3]),
    .AWLEN_AXI4_Slave0(m_awlen[0]),
    .AWLEN_AXI4_Slave1(m_awlen[1]),
    .AWLEN_AXI4_Slave2(m_awlen[2]),
    .AWLEN_AXI4_Slave3(m_awlen[3]),
    .AWLOCK_AXI4_Slave0(m_awlock[0]),
    .AWLOCK_AXI4_Slave1(m_awlock[1]),
    .AWLOCK_AXI4_Slave2(m_awlock[2]),
    .AWLOCK_AXI4_Slave3(m_awlock[3]),
    .AWPROT_AXI4_Slave0(m_awprot[0]),
    .AWPROT_AXI4_Slave1(m_awprot[1]),
    .AWPROT_AXI4_Slave2(m_awprot[2]),
    .AWPROT_AXI4_Slave3(m_awprot[3]),
    .AWQOS_AXI4_Slave0(m_awqos[0]),
    .AWQOS_AXI4_Slave1(m_awqos[1]),
    .AWQOS_AXI4_Slave2(m_awqos[2]),
    .AWQOS_AXI4_Slave3(m_awqos[3]),
    .AWREADY_AXI4_Slave0(m_awready[0]),
    .AWREADY_AXI4_Slave1(m_awready[1]),
    .AWREADY_AXI4_Slave2(m_awready[2]),
    .AWREADY_AXI4_Slave3(m_awready[3]),
    .AWREGION_AXI4_Slave0(m_awregion[0]),
    .AWREGION_AXI4_Slave1(m_awregion[1]),
    .AWREGION_AXI4_Slave2(m_awregion[2]),
    .AWREGION_AXI4_Slave3(m_awregion[3]),
    .AWSIZE_AXI4_Slave0(m_awsize[0]),
    .AWSIZE_AXI4_Slave1(m_awsize[1]),
    .AWSIZE_AXI4_Slave2(m_awsize[2]),
    .AWSIZE_AXI4_Slave3(m_awsize[3]),
    .AWUSER_AXI4_Slave0(m_awuser[0]),
    .AWUSER_AXI4_Slave1(m_awuser[1]),
    .AWUSER_AXI4_Slave2(m_awuser[2]),
    .AWUSER_AXI4_Slave3(m_awuser[3]),
    .AWVALID_AXI4_Slave0(m_awvalid[0]),
    .AWVALID_AXI4_Slave1(m_awvalid[1]),
    .AWVALID_AXI4_Slave2(m_awvalid[2]),
    .AWVALID_AXI4_Slave3(m_awvalid[3]),
    .BID_AXI4_Slave0(m_bid[0]),
    .BID_AXI4_Slave1(m_bid[1]),
    .BID_AXI4_Slave2(m_bid[2]),
    .BID_AXI4_Slave3(m_bid[3]),
    .BREADY_AXI4_Slave0(m_bready[0]),
    .BREADY_AXI4_Slave1(m_bready[1]),
    .BREADY_AXI4_Slave2(m_bready[2]),
    .BREADY_AXI4_Slave3(m_bready[3]),
    .BRESP_AXI4_Slave0(m_bresp[0]),
    .BRESP_AXI4_Slave1(m_bresp[1]),
    .BRESP_AXI4_Slave2(m_bresp[2]),
    .BRESP_AXI4_Slave3(m_bresp[3]),
    .BUSER_AXI4_Slave0(m_buser[0]),
    .BUSER_AXI4_Slave1(m_buser[1]),
    .BUSER_AXI4_Slave2(m_buser[2]),
    .BUSER_AXI4_Slave3(m_buser[3]),
    .BVALID_AXI4_Slave0(m_bvalid[0]),
    .BVALID_AXI4_Slave1(m_bvalid[1]),
    .BVALID_AXI4_Slave2(m_bvalid[2]),
    .BVALID_AXI4_Slave3(m_bvalid[3]),
    .RDATA_AXI4_Slave0(m_rdata[0]),
    .RDATA_AXI4_Slave1(m_rdata[1]),
    .RDATA_AXI4_Slave2(m_rdata[2]),
    .RDATA_AXI4_Slave3(m_rdata[3]),
    .RID_AXI4_Slave0(m_rid[0]),
    .RID_AXI4_Slave1(m_rid[1]),
    .RID_AXI4_Slave2(m_rid[2]),
    .RID_AXI4_Slave3(m_rid[3]),
    .RLAST_AXI4_Slave0(m_rlast[0]),
    .RLAST_AXI4_Slave1(m_rlast[1]),
    .RLAST_AXI4_Slave2(m_rlast[2]),
    .RLAST_AXI4_Slave3(m_rlast[3]),
    .RREADY_AXI4_Slave0(m_rready[0]),
    .RREADY_AXI4_Slave1(m_rready[1]),
    .RREADY_AXI4_Slave2(m_rready[2]),
    .RREADY_AXI4_Slave3(m_rready[3]),
    .RRESP_AXI4_Slave0(m_rresp[0]),
    .RRESP_AXI4_Slave1(m_rresp[1]),
    .RRESP_AXI4_Slave2(m_rresp[2]),
    .RRESP_AXI4_Slave3(m_rresp[3]),
    .RUSER_AXI4_Slave0(m_ruser[0]),
    .RUSER_AXI4_Slave1(m_ruser[1]),
    .RUSER_AXI4_Slave2(m_ruser[2]),
    .RUSER_AXI4_Slave3(m_ruser[3]),
    .RVALID_AXI4_Slave0(m_rvalid[0]),
    .RVALID_AXI4_Slave1(m_rvalid[1]),
    .RVALID_AXI4_Slave2(m_rvalid[2]),
    .RVALID_AXI4_Slave3(m_rvalid[3]),
    .WDATA_AXI4_Slave0(m_wdata[0]),
    .WDATA_AXI4_Slave1(m_wdata[1]),
    .WDATA_AXI4_Slave2(m_wdata[2]),
    .WDATA_AXI4_Slave3(m_wdata[3]),
    .WLAST_AXI4_Slave0(m_wlast[0]),
    .WLAST_AXI4_Slave1(m_wlast[1]),
    .WLAST_AXI4_Slave2(m_wlast[2]),
    .WLAST_AXI4_Slave3(m_wlast[3]),
    .WREADY_AXI4_Slave0(m_wready[0]),
    .WREADY_AXI4_Slave1(m_wready[1]),
    .WREADY_AXI4_Slave2(m_wready[2]),
    .WREADY_AXI4_Slave3(m_wready[3]),
    .WSTRB_AXI4_Slave0(m_wstrb[0]),
    .WSTRB_AXI4_Slave1(m_wstrb[1]),
    .WSTRB_AXI4_Slave2(m_wstrb[2]),
    .WSTRB_AXI4_Slave3(m_wstrb[3]),
    .WUSER_AXI4_Slave0(m_wuser[0]),
    .WUSER_AXI4_Slave1(m_wuser[1]),
    .WUSER_AXI4_Slave2(m_wuser[2]),
    .WUSER_AXI4_Slave3(m_wuser[3]),
    .WVALID_AXI4_Slave0(m_wvalid[0]),
    .WVALID_AXI4_Slave1(m_wvalid[1]),
    .WVALID_AXI4_Slave2(m_wvalid[2]),
    .WVALID_AXI4_Slave3(m_wvalid[3]),
    .ARADDR_AXI4_Master0(s_araddr[0]),
    .ARADDR_AXI4_Master1(s_araddr[1]),
    .ARADDR_AXI4_Master2(s_araddr[2]),
    .ARADDR_AXI4_Master3(s_araddr[3]),
    .ARBURST_AXI4_Master0(s_arburst[0]),
    .ARBURST_AXI4_Master1(s_arburst[1]),
    .ARBURST_AXI4_Master2(s_arburst[2]),
    .ARBURST_AXI4_Master3(s_arburst[3]),
    .ARCACHE_AXI4_Master0(s_arcache[0]),
    .ARCACHE_AXI4_Master1(s_arcache[1]),
    .ARCACHE_AXI4_Master2(s_arcache[2]),
    .ARCACHE_AXI4_Master3(s_arcache[3]),
    .ARID_AXI4_Master0(s_arid[0]),
    .ARID_AXI4_Master1(s_arid[1]),
    .ARID_AXI4_Master2(s_arid[2]),
    .ARID_AXI4_Master3(s_arid[3]),
    .ARLEN_AXI4_Master0(s_arlen[0]),
    .ARLEN_AXI4_Master1(s_arlen[1]),
    .ARLEN_AXI4_Master2(s_arlen[2]),
    .ARLEN_AXI4_Master3(s_arlen[3]),
    .ARLOCK_AXI4_Master0(s_arlock[0]),
    .ARLOCK_AXI4_Master1(s_arlock[1]),
    .ARLOCK_AXI4_Master2(s_arlock[2]),
    .ARLOCK_AXI4_Master3(s_arlock[3]),
    .ARPROT_AXI4_Master0(s_arprot[0]),
    .ARPROT_AXI4_Master1(s_arprot[1]),
    .ARPROT_AXI4_Master2(s_arprot[2]),
    .ARPROT_AXI4_Master3(s_arprot[3]),
    .ARREADY_AXI4_Master0(s_arready[0]),
    .ARREADY_AXI4_Master1(s_arready[1]),
    .ARREADY_AXI4_Master2(s_arready[2]),
    .ARREADY_AXI4_Master3(s_arready[3]),
    .ARREGION_AXI4_Master0(s_arregion[0]),
    .ARREGION_AXI4_Master1(s_arregion[1]),
    .ARREGION_AXI4_Master2(s_arregion[2]),
    .ARREGION_AXI4_Master3(s_arregion[3]),
    .ARSIZE_AXI4_Master0(s_arsize[0]),
    .ARSIZE_AXI4_Master1(s_arsize[1]),
    .ARSIZE_AXI4_Master2(s_arsize[2]),
    .ARSIZE_AXI4_Master3(s_arsize[3]),
    .ARUSER_AXI4_Master0(s_aruser[0]),
    .ARUSER_AXI4_Master1(s_aruser[1]),
    .ARUSER_AXI4_Master2(s_aruser[2]),
    .ARUSER_AXI4_Master3(s_aruser[3]),
    .ARVALID_AXI4_Master0(s_arvalid[0]),
    .ARVALID_AXI4_Master1(s_arvalid[1]),
    .ARVALID_AXI4_Master2(s_arvalid[2]),
    .ARVALID_AXI4_Master3(s_arvalid[3]),
    .AWADDR_AXI4_Master0(s_awaddr[0]),
    .AWADDR_AXI4_Master1(s_awaddr[1]),
    .AWADDR_AXI4_Master2(s_awaddr[2]),
    .AWADDR_AXI4_Master3(s_awaddr[3]),
    .AWBURST_AXI4_Master0(s_awburst[0]),
    .AWBURST_AXI4_Master1(s_awburst[1]),
    .AWBURST_AXI4_Master2(s_awburst[2]),
    .AWBURST_AXI4_Master3(s_awburst[3]),
    .AWCACHE_AXI4_Master0(s_awcache[0]),
    .AWCACHE_AXI4_Master1(s_awcache[1]),
    .AWCACHE_AXI4_Master2(s_awcache[2]),
    .AWCACHE_AXI4_Master3(s_awcache[3]),
    .AWID_AXI4_Master0(s_awid[0]),
    .AWID_AXI4_Master1(s_awid[1]),
    .AWID_AXI4_Master2(s_awid[2]),
    .AWID_AXI4_Master3(s_awid[3]),
    .AWLEN_AXI4_Master0(s_awlen[0]),
    .AWLEN_AXI4_Master1(s_awlen[1]),
    .AWLEN_AXI4_Master2(s_awlen[2]),
    .AWLEN_AXI4_Master3(s_awlen[3]),
    .AWLOCK_AXI4_Master0(s_awlock[0]),
    .AWLOCK_AXI4_Master1(s_awlock[1]),
    .AWLOCK_AXI4_Master2(s_awlock[2]),
    .AWLOCK_AXI4_Master3(s_awlock[3]),
    .AWPROT_AXI4_Master0(s_awprot[0]),
    .AWPROT_AXI4_Master1(s_awprot[1]),
    .AWPROT_AXI4_Master2(s_awprot[2]),
    .AWPROT_AXI4_Master3(s_awprot[3]),
    .AWREADY_AXI4_Master0(s_awready[0]),
    .AWREADY_AXI4_Master1(s_awready[1]),
    .AWREADY_AXI4_Master2(s_awready[2]),
    .AWREADY_AXI4_Master3(s_awready[3]),
    .AWREGION_AXI4_Master0(s_awregion[0]),
    .AWREGION_AXI4_Master1(s_awregion[1]),
    .AWREGION_AXI4_Master2(s_awregion[2]),
    .AWREGION_AXI4_Master3(s_awregion[3]),
    .AWSIZE_AXI4_Master0(s_awsize[0]),
    .AWSIZE_AXI4_Master1(s_awsize[1]),
    .AWSIZE_AXI4_Master2(s_awsize[2]),
    .AWSIZE_AXI4_Master3(s_awsize[3]),
    .AWUSER_AXI4_Master0(s_awuser[0]),
    .AWUSER_AXI4_Master1(s_awuser[1]),
    .AWUSER_AXI4_Master2(s_awuser[2]),
    .AWUSER_AXI4_Master3(s_awuser[3]),
    .AWVALID_AXI4_Master0(s_awvalid[0]),
    .AWVALID_AXI4_Master1(s_awvalid[1]),
    .AWVALID_AXI4_Master2(s_awvalid[2]),
    .AWVALID_AXI4_Master3(s_awvalid[3]),
    .BID_AXI4_Master0(s_bid[0]),
    .BID_AXI4_Master1(s_bid[1]),
    .BID_AXI4_Master2(s_bid[2]),
    .BID_AXI4_Master3(s_bid[3]),
    .BREADY_AXI4_Master0(s_bready[0]),
    .BREADY_AXI4_Master1(s_bready[1]),
    .BREADY_AXI4_Master2(s_bready[2]),
    .BREADY_AXI4_Master3(s_bready[3]),
    .BRESP_AXI4_Master0(s_bresp[0]),
    .BRESP_AXI4_Master1(s_bresp[1]),
    .BRESP_AXI4_Master2(s_bresp[2]),
    .BRESP_AXI4_Master3(s_bresp[3]),
    .BUSER_AXI4_Master0(s_buser[0]),
    .BUSER_AXI4_Master1(s_buser[1]),
    .BUSER_AXI4_Master2(s_buser[2]),
    .BUSER_AXI4_Master3(s_buser[3]),
    .BVALID_AXI4_Master0(s_bvalid[0]),
    .BVALID_AXI4_Master1(s_bvalid[1]),
    .BVALID_AXI4_Master2(s_bvalid[2]),
    .BVALID_AXI4_Master3(s_bvalid[3]),
    .RDATA_AXI4_Master0(s_rdata[0]),
    .RDATA_AXI4_Master1(s_rdata[1]),
    .RDATA_AXI4_Master2(s_rdata[2]),
    .RDATA_AXI4_Master3(s_rdata[3]),
    .RID_AXI4_Master0(s_rid[0]),
    .RID_AXI4_Master1(s_rid[1]),
    .RID_AXI4_Master2(s_rid[2]),
    .RID_AXI4_Master3(s_rid[3]),
    .RLAST_AXI4_Master0(s_rlast[0]),
    .RLAST_AXI4_Master1(s_rlast[1]),
    .RLAST_AXI4_Master2(s_rlast[2]),
    .RLAST_AXI4_Master3(s_rlast[3]),
    .RREADY_AXI4_Master0(s_rready[0]),
    .RREADY_AXI4_Master1(s_rready[1]),
    .RREADY_AXI4_Master2(s_rready[2]),
    .RREADY_AXI4_Master3(s_rready[3]),
    .RRESP_AXI4_Master0(s_rresp[0]),
    .RRESP_AXI4_Master1(s_rresp[1]),
    .RRESP_AXI4_Master2(s_rresp[2]),
    .RRESP_AXI4_Master3(s_rresp[3]),
    .RUSER_AXI4_Master0(s_ruser[0]),
    .RUSER_AXI4_Master1(s_ruser[1]),
    .RUSER_AXI4_Master2(s_ruser[2]),
    .RUSER_AXI4_Master3(s_ruser[3]),
    .RVALID_AXI4_Master0(s_rvalid[0]),
    .RVALID_AXI4_Master1(s_rvalid[1]),
    .RVALID_AXI4_Master2(s_rvalid[2]),
    .RVALID_AXI4_Master3(s_rvalid[3]),
    .WDATA_AXI4_Master0(s_wdata[0]),
    .WDATA_AXI4_Master1(s_wdata[1]),
    .WDATA_AXI4_Master2(s_wdata[2]),
    .WDATA_AXI4_Master3(s_wdata[3]),
    .WLAST_AXI4_Master0(s_wlast[0]),
    .WLAST_AXI4_Master1(s_wlast[1]),
    .WLAST_AXI4_Master2(s_wlast[2]),
    .WLAST_AXI4_Master3(s_wlast[3]),
    .WREADY_AXI4_Master0(s_wready[0]),
    .WREADY_AXI4_Master1(s_wready[1]),
    .WREADY_AXI4_Master2(s_wready[2]),
    .WREADY_AXI4_Master3(s_wready[3]),
    .WSTRB_AXI4_Master0(s_wstrb[0]),
    .WSTRB_AXI4_Master1(s_wstrb[1]),
    .WSTRB_AXI4_Master2(s_wstrb[2]),
    .WSTRB_AXI4_Master3(s_wstrb[3]),
    .WUSER_AXI4_Master0(s_wuser[0]),
    .WUSER_AXI4_Master1(s_wuser[1]),
    .WUSER_AXI4_Master2(s_wuser[2]),
    .WUSER_AXI4_Master3(s_wuser[3]),
    .WVALID_AXI4_Master0(s_wvalid[0]),
    .WVALID_AXI4_Master1(s_wvalid[1]),
    .WVALID_AXI4_Master2(s_wvalid[2]),
    .WVALID_AXI4_Master3(s_wvalid[3])
  );

endmodule : axi4_nic400_fabric_wrapper

`endif
